import Navbar from '@/components/Navbar'
import './globals.css'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'BlogON',
  description: 'Generated by Gamoventure',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <div className=" bg-slate-800 min-w-sm text-slate-50 font-MPlus1p min-h-screen h-max box-border">
          <Navbar />
          <div className="sm:max-3xl:mx-8 mx-4 flex gap-4 flex-wrap justify-center items-center ">
            {children}
          </div>
        </div>
      </body>
    </html>
  )
}
